### ISSUE TITLE
Enhancement request: use only 1 AIB signal for resetting AIB adapter

### ISSUE THREAD

**Issue by dkehlet** [intel/aib-phy-hardware#10]
AIB open source uses two signals for resetting AIB adapter:
    AIB61 u_adapter_tx_pld_rst_n
and
    AIB65 u_adapter_rx_pld_rst_n

AIB spec says that a single reset 
    AIB65 fs_adapter_rstn
should cause the adapter to reset calibration.

Inside the open source the tx and rx adapter section are independently reset.  This request is to perform both tx and rx functions based on AIB65.  One possible means to do this is to edit c3aibadapt_wrap.v's c3aibadapt instantiation as follows:
As Is:
  // Inputs
                           .i_aib_rx_adpt_rst_n (aib_rx_adpt_rst_n), // Templated
                           .i_aib_tx_adpt_rst_n (aib_tx_adpt_rst_n), // Templated
Edited
  // Inputs
                           .i_aib_rx_adpt_rst_n (aib_rx_adpt_rst_n), // Templated
                           .i_aib_tx_adpt_rst_n (aib_rx_adpt_rst_n), // Templated

The desired result is that AIB61 is ignored, and AIB65 performs both a tx and rx adapter reset.

**Comment by xinyang2k** [comment]
This enhancement checked in 6/17/2019
