### ISSUE TITLE
Enhancement request: expose ns_mac_rdy downward from aib_top

### ISSUE THREAD

**Issue by dkehlet** [intel/aib-phy-hardware#12]
ns_mac_rdy should go to AIB49 as an output from the S10 Chiplet.  Please expose ns_mac_rdy as an input at each module port up through aib_top (where it will be ns_mac_rdy[23:0] to expose the signal from each channel).

Note that c3aibadapt sends aib_rx_pma_div66_clk into the aibcr3_top_wrap’s ihssi_pld_pma_clkdiv_rx_user input port.  I think aibcr3_top_wrap’s ihssi_pld_pma_clkdiv_rx_user is the signal coming from AIB49 that should be brought out to aib_top and exposed as the input port ns_mac_rdy.  

I don’t know what the aib_rx_pma_div66_clk wire does in c3aibadapt.  But we have to break it in order to expose ihssi_pld_pma_clkdiv_rx_user up through aib_top.  Would you also check that removing the aib_rx_pma_div66_clk does no harm?

**Comment by xinyang2k** [comment]
This enhancement checked in 6/17/2019
