### ISSUE TITLE
Enhancement: for all channels expose the sideband shift registers

### ISSUE THREAD

**Issue by dkehlet** [intel/aib-phy-hardware#13]
1. For all channels [23:0] expose the slave to master incoming shift register at aib_top, PHY-->MAC
2. For all channels [23:0] expose the master to slave bits corresponding to the outgoing shift register PHY-->MAC and MAC-->PHY
3. Identify the non-reserved bits in aib_top for my convenience :-), for example: 
wire sl_osc_transfer_en = sl_sideband[72];   
wire ms_tx_transfer_en   = ms_sideband[78];

**Comment by xinyang2k** [comment]
This enhancement checked in 6/17/2019
