### ISSUE TITLE
dbg_test_(defines/jtagsm).v

### ISSUE THREAD

**Issue by isaaccleffler** [intel/aib-phy-hardware#2]
Hello Dave,

I am filling this out as a test case for you as requested in your email last week.

LMCO AIB PHY design used two files provided by Intel, 'dbg_test_defines.v' and 'dbg_test_jtagsm.v'.  Neither of these files appear in your AIB repository.  

Given that they are Intel based files, we need your approval to make them available publicly and to my knowledge, we cannot publicly release Intel based files through our GitHub.  

I see two paths to getting this released in it's entirety, let me know if I am missing something here.
1. Intel reviews and posts the RTL as is to the Intel GitHub.
2. Intel reviews the items and approves us to remove any Intel markings and post to LMCO GitHub with no copyright markings.

I only propose #2 because the files originally did not have Intel markings on them when they were originally provided.  Intrinsix added non-proprietary Intel headers in good faith to ensure they were not making a claim to your RTL.

Thank you,

- Isaac -

[Intel Request.zip](https://github.com/intel/aib-phy-hardware/files/2880096/Intel.Request.zip)

**Comment by dkehlet** [comment]
Hi Isaac, the two files are added.  Does that resolve the issue?

**Comment by isaaccleffler** [comment]
Thank you for taking care of this, Dave.  

This will take care of our need.

- Isaac -
