### ISSUE TITLE
Latency mismatch with AIB specification

### ISSUE THREAD

**Issue by pkhanhesi** [intel/aib-phy-hardware#21]
The AIB define that latency of DDR is 3UI (1.5 cycle) and SDR is 1UI (1 cycle)

But simulation on the open code showed that:
   - DDR : TX have 3UI, but RX have 5UI
![image](https://user-images.githubusercontent.com/52446028/62589038-21318280-b8f2-11e9-9d25-c0f63f8e2390.png)
   - SDR:  0.5UI

![sdr_latency](https://user-images.githubusercontent.com/52446028/62589141-7cfc0b80-b8f2-11e9-9c78-94555d0cd25e.PNG)

Please confirm.

**Comment by xinyang2k** [comment]
Here is the clarification of the Spec:
1) The latency in the spec is about AIBIO, it does not include the AIB adapter.
2) Open source includes AIB adapter even though, it is just a Flop there.
3) For the TX DDR path, the spec expect 1 Flop to latch the data, then at the AIBIO, the negative edge data go out first. This is total of 1.5 cycle. (Same as what you have seen in the opensource except the flop is sitting in the AIB adapter).  For the RX DDR path, AIBIO already has 1.5 cycle. The adapter added extra cycle. 

Let me know if this is clear.
