### ISSUE TITLE
Enhancement request: Support for emulation/FPGA

### ISSUE THREAD

**Issue by dklowden** [intel/aib-phy-hardware#23]
The AIB specification RTL model is something that we would like to use within our emulation/FPGA environment. This is to support initial multi-die platform functional modeling, where, emulation/FPGA has the capacity to support larger models.

We are finding that the AIB fails on emulation compilation, one specific example is:
Error     [RTLC-6775]: Fille: /nfs/site/disks/dcg_ifg/users/sncline/builds/sncline_t073_6aug2019/puma-rtl/HW/emu/../src/ebb/AIB/AIB_spec_IP/rtl/aib_ioring.v, Line 2598: Bit/Part/Concatenation select on nc_async_dat_poutp[i] is out of range. Continuing ...

We can help provide more specific/onion peeling confirmation of fixes needed since you might not have the lint checks/emulation checks needed to verify... Initial confirmation is to see if you are willing to work to make the AIB model emulation compliant.

**Comment by xinyang2k** [comment]
We are looking at this.  Thanks for the feedback.

**Comment by xinyang2k** [comment]
Comment from developer:
The aib model is parameterized to support more than 20 IOs  for simulation purpose.
The io_ring rtl is the behavior model for the custom design IOs.
We can help to modify for emulation compliant with the emulation required IOs.

**Comment by dklowden** [comment]
I just want to clarify one point on this request. The emulation support requested was for the full AIB design, including the IO/PHY behavioral model to be abstracted in emulation. For this specific request it was not to support using the actual legacy FPGA AIB interface hardware.

So to clarify, which level of support is being looked at? If it is the full emulation support, including PHY/IO abstraction, this meets our needs. If it is the later focus to support using legacy AIB hardware PHY, this doesn't address the concern.
