### ISSUE TITLE
MAC/PHY signal ns_mac_rdy is not connected from MAC through to the AIB bump

### ISSUE THREAD

**Issue by dkehlet** [intel/aib-phy-hardware#26]
User reported on 9/3/2019 that the MAC/PHY signal ns_mac_rdy is intercepted in the local adapter before it goes to the bump.  The spec has this ns_mac_rdy description:
    For resetting near-side data transfers and communicating MAC readiness for calibration to the far side

Please investigate how the ns_mac_rdy MAC/PHY signal is processed. If as the user says the signal is intercepted locally, we should not necessarily make any change as some designs expect the current behavior.  This may be a "will not fix" issue.

**Comment by xinyang2k** [comment]
ns_mac_rdy is currently a port in c3aibadapt_wrap.v but not used in this file.  The corresponding microbump is io_aib49. Currently this microbump  is tied high. If user want to use ns_mac_rdy, they can connect ns_mac_rdy to i_rx_pma_div66_clk of  c3aibadapt.v file. The opensource IP is not completely complaisance with AIB specification.  It is served as a working reference. Please follow the AIB specification and AIB model for new design.
