### ISSUE TITLE
Warning select out of bound on the model

### ISSUE THREAD

**Issue by pkhanhesi** [intel/aib-phy-hardware#27]
Hi, 
There is a warning of Select index out of bounds at line 2700 under rtl/aib_iorings.v
Seem that the idat0_poutp is not fully parameterized:
![image](https://user-images.githubusercontent.com/52446028/65111688-33313580-da07-11e9-98dc-eb2dfb8eba6a.png)

Could you please check again ?

**Comment by xinyang2k** [comment]
File aib_ioring.v has modified to correct this warning.
