### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by pkhanhesi** [intel/aib-phy-hardware#28]
Hi,
Please help to check 4 connection issues below:

1. 
Tx and Rx both use the same port itxen to control in/out hence it made rxdat18 become X.

Wrong code is on 2133th line.
Right code should be on 2132th line. 

![1](https://user-images.githubusercontent.com/52446028/66194853-9b4a7180-e6bf-11e9-80a8-4744f1833bf8.png)

2.
: Wrong connection on iddren_in1 of rxfck/ rxfckb lead to wrong selection of iddren_out when running in repair mode. 
Expectation: cell rxfck/ rxfckb keep iddren_out = 1 in repair mode.

Wrong code is on 1970th , 2554th line.
Right code should be on 1971th, 2555th line. 

//aib_ioring
 
![2a](https://user-images.githubusercontent.com/52446028/66194969-d8aeff00-e6bf-11e9-9c69-a9120b9e6b27.png)
![2b](https://user-images.githubusercontent.com/52446028/66194990-e2d0fd80-e6bf-11e9-8985-85b90a8905f4.png)

 //aib_redundancy
 
![2c](https://user-images.githubusercontent.com/52446028/66195007-ebc1cf00-e6bf-11e9-95c0-5e9159055f8d.png)
//tb_top
![2d](https://user-images.githubusercontent.com/52446028/66195013-f0868300-e6bf-11e9-8793-b6e18fb0f379.png)

3.
similar  issue with above issue with 2 more cells: rxclk/ rxclkb.
Fix: .iddren_in1(iddren), .ilaunch_clk_in0(vssl_aib).
Wrong code is on 1743th , 2325th line.
Right code should be on 1744th, 2326th line.
![3a](https://user-images.githubusercontent.com/52446028/66195130-2b88b680-e6c0-11e9-8dd3-410d104f9ed3.png)
![3b](https://user-images.githubusercontent.com/52446028/66195196-4eb36600-e6c0-11e9-9059-8638bf1b9ca2.png)

4. 
2 connection bugs on aib_ioring module of Intel model. (txdat8/ txdat9).

Fail reason: 
As running SDR mode without repair function (mission mode), Intel will check condition iddren then if SDR mode => invert clk_in from m_ns_fwd_clk into ~m_ns_fwd_clk then assign it to txfcko (ns_fwd_clk). 
 // aib_ioring.v

![4a](https://user-images.githubusercontent.com/52446028/66195245-6a1e7100-e6c0-11e9-90c8-acb732b59166.png)
But when running SDR mode with repair function, Intel forgot that condition (check iddren) and assign directly m_ns_fwd_clk to ns_fwd_clk.
->	It create a wrong latency (only 1.5clk not 2clks with SDR mode).
Wrong code is on 475th,476th / 1152th,1153th line.
Right code should be on 477th,478th / 1154th,1155th line.
![4b](https://user-images.githubusercontent.com/52446028/66195264-74d90600-e6c0-11e9-8244-6939dc7e23d3.png)
![4c](https://user-images.githubusercontent.com/52446028/66195269-77d3f680-e6c0-11e9-89e9-b670b35636be.png)

Best regards,

**Comment by dkehlet** [comment]
Hi please give us until last week of October for our team member to return.

**Comment by xinyang2k** [comment]
Thanks for the feedback. The issue has been fixed in 10/23/2019.
Files the modified are:
rtl/aib_channel.v
rtl/aib_sr_sl.v
rtl/aib_sr_ms.v
rtl/aib_ioring
