### ISSUE TITLE
Sideband RTL defaults don't seem to match AIB Spec tables 

### ISSUE THREAD

**Issue by rbaracka** [intel/aib-phy-hardware#30]
The commented assigns below from from rtl/aib_channel.v don't seem to completely match Tables 50 and 51.

assign ms_data_fr_core[80:0] = {ms_osc_transfer_en,
                                1'b1,
                                ms_tx_transfer_en,
                                2'b11,
                                ms_rx_transfer_en,
                                ms_rx_dll_lock,
                                5'b11111,
                                ms_tx_dcc_cal_done,
                                1'b0,
                                1'b0,                    // Bit 66, AIB_Intel_Specification 1_2 Table 50 says '1'?
                                ms_external_cntl_65_8[57:0],
                                1'b1,
                                1'b0,
                                1'b0,                    // Bit  5, AIB_Intel_Specification 1_2 Table 50 says '1'?
                                ms_external_cntl_4_0[4:0]};

assign sl_data_fr_core[72:0] = {sl_osc_transfer_en,
                                1'b0,
                                sl_rx_transfer_en,
                                sl_rx_dcc_dll_lock_req,
                                sl_rx_dll_lock,
                                3'b0,
                                sl_tx_transfer_en,
                                sl_tx_dcc_dll_lock_req,
                                1'b0,
                                1'b0,
                                1'b0,                    // Bit 60, AIB_Intel_Specification 1_2 Table 51 says '1'?
                                1'b0,
                                1'b0,                    // Bit 58, AIB_Intel_Specification 1_2 Table 51 says '1'?
                                sl_external_cntl_57_32[25:0],
                                sl_tx_dcc_cal_done,
                                sl_external_cntl_30_28[2:0],
                                1'b0, sl_external_cntl_26_0[26:0]};

**Comment by xinyang2k** [comment]
Thanks for the feedback and review!
The bug has been fixed for the check in of 10/23/2019. The file that modified is rtl/aib_channel.v
