### ISSUE TITLE
Connection device_detect and por signal in the model

### ISSUE THREAD

**Issue by pkhanhesi** [intel/aib-phy-hardware#34]
Hi,
In the model, file aib_model/rtl/aib_aux_channel.v, there is 2 issue:
1. Device detect: 
   it's refering directly to the iopad device_detect signal.
   We think it's better to have and port implemented to connect to the MAC.
   Suggestion to add line 20 and 39 in below picture:
    ![1](https://user-images.githubusercontent.com/52446028/69839967-5e989200-128c-11ea-8511-1bae09828bcd.png)

2. POR signal
  In above picture, POR is create by and AND gate between the normal and redundancy signal.
  It's better to have OR gate implementation because we will want both POR stable 0 before claim 
  the Power on reset is finished.
  Please help confirm if this understanding is correct.

Thank you and best regards,

**Comment by dkehlet** [comment]
1. Agree on the output.  When in slave mode, device_detect should go from aib PHY to MAC.  In the last few months we decided to call this PHY-->MAC signal "m_device_detect".  As written this code cannot fully model the slave.

However, the code does not correctly model redundancy for device_detect.  As slave, there is only 1 device_detect input buffer.  No ANDing or ORing should be done.  "For Slaves, the two device_detect bumps should be connected by Slave on-die wiring before the Slave input buffer."  As master, there is only 1 device_detect output buffer. "For Masters, the two device_detect bumps should be connected by Master on-die wiring after the Master output buffer."  This should be corrected in the model code.

2. POR is similar.  There is only one input buffer (Master) or output buffer (Slave). "For Masters, the two por bumps should be connected by Master on-die wiring before the Master input buffer." 
"For Slaves, the two por bumps should be connected by Slave on-die wiring after the Slave output buffer."  No ANDing or ORing should be done.  This should also be corrected in the model code.

See figures 12 and 13 in the "AIB Usage Note" v1.2.

**Comment by xinyang2k** [comment]
Check Commits on Dec 9, 2019 commit. This issue is closed by the RTL change.
