### ISSUE TITLE
Need to identify where hardened synchronizer flops should be entered

### ISSUE THREAD

**Issue by dkehlet** [intel/aib-phy-hardware#35]
The aib_lib needs to identify in the code where hardened synchronizer flops should be used.  For example in the file aibcr3_sync_3ff.v, the code should not be synthesized.  Instead, this code should be contained within an 
`ifdef BEHAVIORAL
and the `else should contain a $display warning message -- this is where the technology dependent hardened flops should be entered.
RTL simulation then works with 
+define+BEHAVIORAL
but synthesis will not produce a functional netlist until the `else section is filled in.

**Comment by xinyang2k** [comment]
Solved in commit 89
