### ISSUE TITLE
synthesis 

### ISSUE THREAD

**Issue by liuzixuan1212** [intel/aib-phy-hardware#42]
Hi 

I want to use this interface in my new project. Does this RTL code have been synthesis before. If it has been synthesis, can you tell me about your synthesis environment and how it is synthesis.

Thanks

**Comment by dkehlet** [comment]
Hello liuzixuan1212,

Would you please submit this issue to the
github.com/chipsalliance/aib-phy-hardware
repo?

We've relocated AIB into the CHIPS Alliance.

Thanks,  Dave

**Comment by liuzixuan1212** [comment]
Hi Dave 

OK, thanks for help.

Thanks, Zixuan
